Nabar is ready
WildCodeSchool/2023-09-JS-Lille-P3-Afac pull request #10
Opened 2023-12-21 15:25 UTC by Romlion

2023-12-21 15:32 UTC, Rayane0823 approved these changes

2023-12-21 15:36 UTC, LucasMerino10 approved these changes

2023-12-21 15:38 UTC, pagouillart approved these changes

2023-12-21 16:19 UTC, Cyrildab approved these changes

2023-12-21 16:25 UTC, Yoann-Fortin requested changes

2023-12-21 16:25 UTC, Yoann-Fortin commented on frontend/src/components/NavBar/NavBar.jsx
> +function Nav() {
Why is your component name different from your file name?

2023-12-22 09:44 UTC, Yoann-Fortin approved these changes

2023-12-22 10:37 UTC, merged