Profil Page With Responsive
WildCodeSchool/2023-09-JS-Lille-P3-Afac pull request #15
Opened 2024-01-04 15:48 UTC by pagouillart

2024-01-04 16:00 UTC, Rayane0823 approved these changes

2024-01-04 16:18 UTC, Cyrildab approved these changes

2024-01-05 08:39 UTC, Romlion approved these changes

2024-01-05 08:39 UTC, LucasMerino10 approved these changes

2024-01-05 08:50 UTC, Yoann-Fortin requested changes

2024-01-05 08:50 UTC, Yoann-Fortin commented on frontend/src/components/Profil/ProfilCard.jsx
> +    <section className="profilCard">
Reversal of required tags

2024-01-05 08:50 UTC, Yoann-Fortin commented on frontend/src/components/Profil/ProfilCard.jsx
> +      <article className="profilInfo">
Reversal of required tags

2024-01-05 10:15 UTC, pagouillart commented on frontend/src/components/Profil/ProfilCard.jsx
> +    <section className="profilCard">
done

2024-01-05 10:15 UTC, pagouillart commented on frontend/src/components/Profil/ProfilCard.jsx
> +      <article className="profilInfo">
done

2024-01-05 10:16 UTC, Yoann-Fortin approved these changes

2024-01-05 10:21 UTC, merged