add postartwork page
WildCodeSchool/2023-09-JS-Lille-P3-Afac pull request #28
Opened 2024-01-10 09:47 UTC by Cyrildab

2024-01-10 09:48 UTC, Rayane0823 approved these changes

2024-01-10 12:07 UTC, LucasMerino10 approved these changes

2024-01-10 12:34 UTC, pagouillart approved these changes

2024-01-10 13:05 UTC, Romlion approved these changes

2024-01-10 13:40 UTC, Yoann-Fortin commented on frontend/src/components/PostArtwork/PostArtwork.jsx
> +        <input
Button is better

2024-01-11 11:13 UTC, Yoann-Fortin requested changes

2024-01-11 11:13 UTC, Yoann-Fortin commented on frontend/src/components/PostArtwork/PostArtwork.jsx
> +        <button type="button" htmlFor="submit" className="form__label--hidden">
htmlFor doesn't exist for a button

2024-01-11 11:13 UTC, Yoann-Fortin commented on frontend/src/components/PostArtwork/PostArtwork.jsx
> +        <input
Button type submit, not button and input

2024-01-11 13:29 UTC, Yoann-Fortin approved these changes

2024-01-11 13:44 UTC, merged