add return main menu button
WildCodeSchool/2023-09-JS-Lille-P3-Afac pull request #29
Opened 2024-01-10 11:19 UTC by Cyrildab

2024-01-10 12:43 UTC, Romlion approved these changes

2024-01-10 13:06 UTC, Rayane0823 approved these changes

2024-01-10 13:14 UTC, Romlion approved these changes

2024-01-10 13:23 UTC, pagouillart approved these changes

2024-01-10 13:29 UTC, LucasMerino10 approved these changes

2024-01-11 11:07 UTC, Yoann-Fortin requested changes

2024-01-11 11:07 UTC, Yoann-Fortin commented on frontend/src/components/ReturnMainMenuButton/ReturnMainMenuButton.jsx
> +          X
With an aria-label please

2024-01-11 11:07 UTC, Yoann-Fortin commented on frontend/src/components/ReturnMainMenuButton/ReturnMainMenuButton.scss
> +  font-size: 15px;
Responsive value for font-size please

2024-01-11 13:27 UTC, Yoann-Fortin approved these changes

2024-01-11 13:33 UTC, merged