Artwork popUp + responsive + test data in GlobalContext
WildCodeSchool/2023-09-JS-Lille-P3-Afac pull request #6
Opened 2023-12-20 11:46 UTC by LucasMerino10

2023-12-21 08:40 UTC, pagouillart approved these changes

2023-12-21 13:19 UTC, Rayane0823 approved these changes

2023-12-21 15:13 UTC, Cyrildab approved these changes

2023-12-22 09:46 UTC, Yoann-Fortin requested changes
The code will not pass the W3C validator

2024-01-03 17:13 UTC, closed without merging