Adding the homepage carousel component
WildCodeSchool/2023-09-JS-Lille-P3-Afac pull request #8
Opened 2023-12-21 08:37 UTC by Rayane0823

2023-12-21 13:16 UTC, Cyrildab approved these changes

2023-12-21 13:34 UTC, LucasMerino10 approved these changes

2023-12-21 13:36 UTC, LucasMerino10 approved these changes

2023-12-21 15:20 UTC, pagouillart approved these changes

2023-12-21 15:45 UTC, Yoann-Fortin requested changes

2023-12-21 15:45 UTC, Yoann-Fortin commented on frontend/src/components/Carousel/Carousel.scss
> +.alice-carousel__prev-btn {
2 class with same style ?

2023-12-21 15:45 UTC, Yoann-Fortin commented on frontend/src/components/Carousel/Carousel.scss
> +.alice-carousel__next-btn {
2 class with same style ?

2023-12-21 15:45 UTC, Yoann-Fortin commented on frontend/src/components/Carousel/Carousel.scss
> +  top: 70vh;
bottom is better

2023-12-21 15:45 UTC, Yoann-Fortin commented on frontend/src/components/Carousel/Carousel.scss
> +  flex-direction: row-reverse;
Seriously ?

2023-12-21 15:45 UTC, Yoann-Fortin commented on frontend/src/components/Carousel/Carousel.scss
> +  font-size: 14.5px;
No px with sont-size

2023-12-21 15:45 UTC, Yoann-Fortin commented on frontend/src/components/Carousel/Carousel.scss
> +  font-size: 15px;
Again here

2023-12-21 15:45 UTC, Yoann-Fortin commented on frontend/src/components/Carousel/Carousel.scss
> +  font-size: 30px;
And here

2023-12-21 15:45 UTC, Yoann-Fortin commented on frontend/src/components/Carousel/Carousel.scss
> +  top: 89%;
Bottom is better

2023-12-21 15:45 UTC, Yoann-Fortin commented on frontend/src/components/Carousel/Carousel.scss
> +  font-size: 28px;
Always no px to font-size

2023-12-21 15:45 UTC, Yoann-Fortin commented on frontend/src/components/Carousel/Carousel.scss
> +  top: 89%;
bottom is better again

2023-12-21 15:45 UTC, Yoann-Fortin commented on frontend/src/components/Carousel/Carousel.scss
> +  font-size: 30px;
Here again

2023-12-21 15:45 UTC, Yoann-Fortin commented on frontend/src/components/Carousel/Carousel.scss
> +  top: 89%;
Again

2023-12-21 15:45 UTC, Yoann-Fortin commented on frontend/src/components/Carousel/Carousel.jsx
> +            <h1 className="carousel-slide-visit_text carousel-first-slide-visit_text">
3 h1 in same page ?

2023-12-21 15:45 UTC, Yoann-Fortin commented on frontend/src/components/Carousel/Carousel.jsx
> +        <p className="hometext">
hand-cut phrase?

2023-12-21 15:45 UTC, Yoann-Fortin commented on frontend/src/components/Carousel/Carousel.jsx
> +      <section className="carousel-container">
Wrong tag html

2023-12-21 15:45 UTC, Yoann-Fortin commented on frontend/src/components/Carousel/Carousel.jsx
> +        <AliceCarousel
Keyboard navigation impossible with this library

2023-12-22 14:56 UTC, Yoann-Fortin approved these changes

2024-01-04 09:18 UTC, Romlion approved these changes

2024-01-04 09:32 UTC, pagouillart approved these changes

2024-01-04 11:04 UTC, Cyrildab approved these changes

2024-01-05 12:33 UTC, Yoann-Fortin approved these changes

2024-01-05 15:17 UTC, merged