Adding the Homepage menu component
WildCodeSchool/2023-09-JS-Lille-P3-Afac pull request #9
Opened 2023-12-21 11:01 UTC by Rayane0823

2023-12-21 11:03 UTC, pagouillart approved these changes

2023-12-21 13:20 UTC, LucasMerino10 approved these changes

2023-12-21 15:15 UTC, Cyrildab approved these changes

2023-12-21 15:28 UTC, Yoann-Fortin requested changes

2023-12-21 15:28 UTC, Yoann-Fortin commented on frontend/src/components/HomePageMenu/HomePageMenu.jsx
> +      <section className="homepage-menu-buttons-container">
This tag container isn't adapted

2023-12-21 15:28 UTC, Yoann-Fortin commented on frontend/src/components/HomePageMenu/HomePageMenu.jsx
> +        <button
Refactoring is possible here

2023-12-21 15:28 UTC, Yoann-Fortin commented on frontend/src/components/HomePageMenu/HomePageMenu.jsx
> +    <nav className="homepage-menu-container">
Wrong tag html for this implementation

2024-01-04 11:15 UTC, Romlion approved these changes

2024-01-04 11:16 UTC, Cyrildab approved these changes

2024-01-05 12:35 UTC, Yoann-Fortin approved these changes

2024-01-05 14:51 UTC, merged